version: '3.8'

services:
  pacmusic-prod:
    image: "${APP_IMAGE}:${APP_TAG}"
    container_name: pacmusic-prod
    restart: always
    environment:
      MINIO_ENDPOINT: ${MINIO_PROD_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_PROD_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_PROD_SECRET_KEY}
    ports:
      - "${APP_PROD_PORT}:5000"
    networks:
      - pacmusic-network

networks:
  pacmusic-network:
    driver: bridge
    name: pacmusic-network
